url: "http://aliramadhan.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ali Ramadhan" # the name of your site, e.g. ACME Corp.

markdown: kramdown
highlighter: none  # We will use highlight.js
