url: "http://aliramadhan.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ali Ramadhan" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-toc

toc:
  min_level: 1
  max_level: 2
  ordered_list: yes
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: toc-list
  sublist_class: toc-sublist
  item_class: toc-entry
  item_prefix: toc-
